const top100Brands = [
  "Alvarado Street Bakery",
  "Arizmendi Bakery",
  "Au Bon Pain",
  "Avalon International Breads",
  "Big Apple Bagels",
  "Blue Chip Cookies",
  "Boudin Bakery",
  "Breadsmith",
  "Carlo's Bake Shop",
  "Cavanagh Company",
  "The Claxton Bakery",
  "Collin Street Bakery",
  "Crumbs Bake Shop",
  "Flowers Foods",
  "Great Harvest Bread Company",
  "Italian Peoples Bakery",
  "King's Hawaiian",
  "Kossar's Bialys",
  "La Segunda Central Bakery",
  "Le Macaron",
  "Levain Bakery",
  "Liz Lovely",
  "Martin's Famous Pastry Shoppe, Inc.",
  "Mrs. Fields",
  "Orwasher's bakery",
  "Racine Danish Kringles",
  "Schmidt Baking Company",
  "Semifreddi's Bakery",
  "Sprinkles Cupcakes",
  "Sunbeam Bread",
  "United States Bakery",
  "Voodoo Doughnut",
  "Westminster Cracker Company",
  "The Andersons",
  "Archer Daniels Midland",
  "Bob's Red Mill",
  "Bunge Limited",
  "Cargill",
  "CHS Inc.",
  "ContiGroup Companies",
  "Fuji Food",
  "Gavilon",
  "King Arthur Flour",
  "Kuli Kuli, Inc.",
  "The Leavitt Corporation",
  "Little Crow Foods",
  "Love Grown Foods",
  "Magnolia Bakery",
  "MFA Incorporated",
  "Monsanto",
  "Peanut Butter & Co.",
  "POET",
  "Riceland Foods",
  "Two Degrees Food",
  "U.S. Mills",
  "United Cooperative",
  "Abdallah Candies",
  "Amano Artisan Chocolate",
  "American Licorice Company",
  "Annabelle Candy Company",
  "Askinosie Chocolate",
  "Boyer Brothers",
  "Brach's",
  "Brown and Haley",
  "Carolina Foods",
  "Chagrin Falls Popcorn Shop",
  "Chocolove",
  "Dagoba Chocolate",
  "Dan's Chocolates",
  "Dylan's Candy Bar",
  "Friesinger's Candies",
  "Georgetown Cupcake",
  "Gertrude Hawk Chocolates",
  "Giambri's Quality Sweets",
  "Goetze's Candy Company",
  "Guittard Chocolate Company",
  "Idaho Candy Company",
  "Impact Confections",
  "Jelly Belly",
  "Joyva",
  "Just Born",
  "Kegg's Candies",
  "Mast Brothers",
  "Marich Confectionery",
  "Reed's Candy",
  "Rocky Mountain Chocolate Factory",
  "Sanders Confectionery",
  "Sarris Candies",
  "Scharffen Berger Chocolate Maker",
  "Schimpff's Confectionery",
  "See's Candies",
  "Smarties Candy Company",
  "Somebody's Mother's Chocolate Sauce",
  "Spangler Candy Company",
  "Taza Chocolate",
  "TCHO",
  "Unreal Brands",
  "The Warrell Corporation",
  "Whetstone Chocolates",
  "Whitman's",
  "All American Foods",
  "Alpenrose Dairy",
  "Aurora Organic Dairy",
  "BelGioioso Cheese",
  "Bittersweet Plantation Dairy",
  "Blue Bell Creameries",
  "Brewster Dairy",
  "Byrne Dairy",
  "Cabot Creamery",
  "Cal-Maine",
  "Cass-Clay",
  "Chaseholm Farm Creamery",
  "Clover Stornetta Farms",
  "Cowgirl Creamery",
  "Crystal Creamery",
  "Cypress Point Creamery",
  "Dairy Farmers of America",
  "Darigold",
  "DCI Cheese Company",
  "Dean Foods",
  "Ellsworth Cooperative Creamery",
  "Galliker's",
  "Gossner Foods",
  "Grafton Village Cheese Company",
  "Happy Cow Creamery",
  "Hershey Creamery Company",
  "Hilmar Cheese Company",
  "Horizon Organic",
  "HP Hood",
  "Joseph Gallo Farms",
  "Junket",
  "Land O'Lakes",
  "Leprino Foods",
  "Lifeway Foods",
  "Marin French Cheese Company",
  "Maytag Dairy Farms",
  "Murray's Cheese",
  "Nature's Harmony Farm",
  "Organic Valley",
  "Penn State University Creamery",
  "Pierre's Ice Cream Company",
  "Point Reyes Farmstead Cheese Company",
  "Prairie Farms Dairy",
  "Rogue Creamery",
  "Sargento",
  "Schoep's Ice Cream",
  "Schreiber Foods",
  "Shamrock Farms",
  "Siggi's Dairy",
  "Smiling Hill Farm",
  "SmithFoods",
  "Straus Family Creamery",
  "Sunshine Dairy",
  "Sweet Grass Dairy",
  "Tillamook County Creamery Association",
  "United Dairy Farmers",
  "Vermont Creamery",
  "Wainwright Dairy",
  "Winchester Cheese Company",
  "Winder Farms",
  "Wisconsin Cheeseman",
  "Yancey's Fancy",
  "Yarnell Ice Cream Co.",
  "A-Treat Bottling Company",
  "Adirondack Beverages",
  "American Beverage Association",
  "Appalachian Brewing Company",
  "Arizona Beverage Company",
  "Bai Brands",
  "Boylan Bottling Company",
  "Brown-Forman",
  "Castle Brands",
  "Cawy Bottling Company",
  "Crunk Energy Drink",
  "Day's Beverages",
  "Guayakí",
  "Hint Water",
  "Hosmer Mountain Soda",
  "Ice River Springs",
  "Jones Soda",
  "Kern's",
  "Kristian Regale",
  "Luzianne",
  "Manhattan Special",
  "Martinelli's",
  "Matt Brewing Company",
  "Molson Coors Brewing Company",
  "Monarch Beverage, Inc.",
  "National Beverage",
  "Natrona Bottling Company",
  "Numi Organic Tea",
  "Old Orchard Brands",
  "Oogavé",
  "Peet's Coffee & Tea",
  "Poland Spring",
  "Polar Beverages",
  "R. Torre & Company, Inc.",
  "Red Diamond",
  "Steaz",
  "Street King",
  "Talking Rain",
  "Tavalon Tea",
  "Tazo",
  "Tröegs Brewing Company",
  "Turkey Hill",
  "Vanberg & DeWulf",
  "White Rock Beverages",
  "Who's Your Daddy, Inc.",
  "Albertsons",
  "Dot Foods",
  "Gordon Food Service",
  "Kroger",
  "Performance Food Group",
  "Publix",
  "Reyes Holdings",
  "Saladino's Inc",
  "SuperValu",
  "US Foods",
  "Walmart",
  "Whole Foods Market",
  "Winder Farms",
  "Winn Dixie",
  "A. Zerega's Sons, Inc.",
  "Bruce Foods",
  "Brynwood Partners",
  "Bush Brothers and Company",
  "Catterton Partners",
  "Cherrybrook Kitchen",
  "Colavita",
  "Cuisine Solutions",
  "Deep Foods",
  "Eden Foods Inc.",
  "Flagship Food Group",
  "Goya Foods",
  "Gustobene",
  "Isaly's",
  "Krinos Foods",
  "Kronos Foods",
  "La Loma Foods",
  "Luck's Incorporated",
  "Manischewitz",
  "Newman's Own",
  "Rhee Bros., Inc.",
  "Richelieu Foods",
  "Rosa Food",
  "Sclafani Foods",
  "Seneca Foods",
  "Streit's",
  "Tabatchnick",
  "Trappey's Hot Sauce (B&G Foods)",
  "Vitarroz",
  "Frozen foods",
  "Amy's Kitchen",
  "Bellisio Foods",
  "Captain Ken's Foods",
  "Edwards Baking",
  "Fred's Frozen Foods",
  "K&N's Foods USA",
  "Mrs. T's Pierogies",
  "Peas of Mind",
  "Pero Family Farms Food Company",
  "Reser's Fine Foods",
  "Rhino Foods",
  "Ruiz Foods",
  "Schwan Food Company",
  "The Bauman Family",
  "Blue Diamond Growers",
  "Buddy Fruits",
  "Calavo Growers",
  "Del Monte Foods",
  "Dole Food Company",
  "Driscoll's",
  "Franklin Baker Company",
  "Fresh Del Monte Produce",
  "Frieda's Inc.",
  "Hollandia Produce",
  "Idahoan Foods",
  "Limoneira",
  "Maui Pineapple Company",
  "The Morning Star Company",
  "Ocean Spray",
  "Organically Grown Company",
  "Pero Family Farms Food Company",
  "Red Gold",
  "Simple and Crisp",
  "Sunkist Growers, Incorporated",
  "Taylor Farms",
  "Turbana",
  "Wish Farms",
  "Boar's Head Provision Company",
  "Burgers' Smokehouse",
  "Columbus Salame",
  "Dakota Beef",
  "Daniele, Inc.",
  "D'Artagnan",
  "Dietz & Watson",
  "Empire Kosher",
  "Foster Farms",
  "Hatfield Quality Meats",
  "Heritage Foods USA",
  "Hormel",
  "Kansas City Steak Company",
  "Kiolbassa Sausage",
  "Koch Foods",
  "Koegel Meat Company",
  "Lobel's of New York",
  "Marathon Enterprises, Inc.",
  "Molinari's",
  "National Beef Packing Company",
  "Niman Ranch",
  "Norbest",
  "Nueske's Applewood Smoked Meats",
  "Omaha Steaks",
  "Parker House Sausage Company",
  "Pat LaFrieda Meat Purveyors",
  "Perdue Farms",
  "Plumrose USA",
  "Robertson's Hams",
  "Tallgrass Beef Company",
  "Usinger's",
  "Zacky Farms",
  "B.R. Guest",
  "Bloomin' Brands",
  "Bravo Brio Restaurant Group",
  "The Briad Group",
  "Brinker International",
  "Burger King",
  "Darden Restaurants",
  "Del Frisco's Restaurant Group",
  "Delaware North",
  "Dine Brands Global",
  "Dunkin' Brands",
  "Global Franchise Group",
  "Landry's, Inc.",
  "Lettuce Entertain You Enterprises",
  "Luby's",
  "McDonald's",
  "Oberweis Dairy",
  "Ovation Brands",
  "Panera Bread",
  "Real Mex Restaurants",
  "Restaurants Unlimited Inc",
  "Roark Capital Group",
  "Sentinel Capital Partners",
  "Starbucks",
  "Stockade Companies",
  "The Wendy's Company",
  "Yum! Brands",
  "Axium Foods",
  "Beer Nuts",
  "Blair's Sauces and Snacks",
  "Casa Sanchez Foods",
  "Charles Chips",
  "Dakota Style",
  "Elmer's Fine Foods",
  "Golden Flake",
  "J & J Snack Foods",
  "Jel Sert",
  "Kar's Nuts",
  "Martin's Potato Chips",
  "McKee Foods",
  "Mike-sell's",
  "Mrs. Fisher's",
  "Oberto Sausage Company",
  "Old Dutch Foods",
  "Robert's American Gourmet Food",
  "Rudolph Foods",
  "Shearer's Foods",
  "Snak King",
  "Snyder's-Lance",
  "Thanasi Foods",
  "Utz Quality Foods",
  "Wise Foods",
  "Wyandot Snacks",
  "Safeway",
  "Value Corner",
  "QFC",
  "Signature Select",
  "Badia Spices",
  "Basic Food Flavors",
  "Crystal Hot Sauce",
  "Dave's Gourmet",
  "Dog-Gone Sauce",
  "Frank's RedHot",
  "French's",
  "Frontier Natural Products Co-op",
  "Gold Pure Food Products Co.",
  "Herlocher Foods",
  "Huy Fong Foods",
  "J&D's Down Home Enterprises",
  "McCormick & Company",
  "Mezzetta",
  "Mrs. Cubbison's Foods",
  "Mt. Olive Pickle Company",
  "Odell's",
  "Plochman's",
  "Pompeian, Inc.",
  "Pure Indian Foods",
  "Reily Foods Company",
  "Silver Spring Foods",
  "Solo Foods",
  "Tabasco sauce",
  "Tapatío hot sauce",
  "Texas Pete",
  "Urban Accents",
  "Wickles",
  "Wing-Time",
  "Amalgamated Sugar Company",
  "American Crystal Sugar Company",
  "American Sugar Refining",
  "Michigan Sugar",
  "Spreckels Sugar Company",
  "US Sugar Corporation",
  "Western Sugar Cooperative",
  "Campbell Soup Company",
  "The Coca-Cola Company",
  "ConAgra Foods",
  "General Mills",
  "Hain Celestial Group",
  "The Hershey Company",
  "Hormel",
  "Ingredion",
  "The J.M. Smucker Company",
  "Kellogg's",
  "Keurig Dr Pepper",
  "Kraft Heinz",
  "Mars, Incorporated",
  "McCormick & Company",
  "Monarch Beverage Company",
  "Mondelez International",
  "PepsiCo",
  "Post Holdings",
  "Rich Products",
  "Seaboard Corporation",
  "T. Marzetti Company",
  "Tootsie Roll Industries",
  "TreeHouse Foods",
  "Tyson Foods",
  "WhiteWave Foods",
  "Zevia",
];

export default top100Brands;