import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(() => ({
  imageUploader: {
    position: 'relative',
    width: 'fit-content',
    margin: 'auto',
    height: 'max(10vh, auto)',
    minHeight: '160px',
    '& img': {
      'border': '4px solid white',
      height: '200px',
      maxWidth: '200px',
    },
  },
  removeImageBtn: {
    content: '"X"',
    position: 'absolute',
    display: 'block',
    top: '0%',
    right: '-5%',
    borderRadius: '50%',
    height: '45px',
    width: '45px',
    color: '#e23535',
    backgroundColor: 'white',
    border: '5px solid #cc3131',
    fontSize: '1.6em',
    fontWeight: '900',
    '&:hover': {
      backgroundColor: '#f3f3f3',
      color: '#ab1515',
      border: '5px solid #ab1515',
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
    },
  },
  productThumbnailInput: {
    outlineOffset: '-10px',
    height: '200px',
    margin: 'auto',
    maxWidth: '250px',
    display: 'block',
    marginBottom: '1em',
    padding: '10px',
    backgroundColor: '#def0ff',
  },
  imageInputContainer: {
    border: '2px dashed #b29696',
    background: '#f0f4f7',
    height: '100%',
    width: 'fit-content',
    margin: 'auto',
    position: 'relative',
    '& input': {
      width: '80%',
      padding: '1em',
      paddingBottom: '0',
      color: '#717171',
      '& btn': {
        color: 'red',
      },
      margin: 'auto',
      height: '100%',
      minHeight: '200px',
    },
  },
  searchPopup: {
    position: 'absolute',
    width: '20%',
    height: '20%',
    padding: '0.75em 0.25em',
    fontSize: '2em',
    top: '25%',
    left: '-32%',
    backgroundColor: 'orange',
    color: 'white',
    'border': '3px solid #deaa6a',
    '@media (max-width:700px)': {
      top: '60%',
      left: '-2%',
      width: '95%',
    },
  },
  scanUPCBtn: {
    maxWidth: '100px',
    backgroundColor: '#375bf3',
    '&:hover': {
      backgroundColor: '#284adb',
    },
    '& svg': {
      color: 'navy',
      padding: '0.25em',
      position: 'sticky',
      margin: 'auto',
    },
    borderColor: '#1f3cb8',
    borderRadius: '4px',
    textAlign: 'center',
    fontWeight: '600',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    '& p': {
      display: 'inline',
      margin: 'auto',
      position: 'relative',
      bottom: '8px',
      padding: '0',
    },
    position: 'absolute',
    width: '20%',
    height: '20%',
    padding: '0.75em 0.25em',
    fontSize: '2em',
    top: '25%',
    right: '-32%',
    color: 'white',
    'border': '3px solid #deaa6a',
    '@media (max-width:700px)': {
      top: '60%',
      left: '-2%',
      width: '95%',
    },
  },
}));
