import { makeStyles } from "@material-ui/core/styles"

export default makeStyles((theme) => ({
  demoImg: {
    zIndex: "60",
    maxWidth: "90vw",
    maxHeight: "50vh",
    margin: "auto",
    "display": "block",
    "marginLeft": "auto",
    "marginRight": "auto",
  },
  accountLink: {
    "flexDirection": "row",
    "borderRadius": "38px",
    "borderWidth": "0px",
    "padding": "0.5em 2em",
    margin: "1em",
    "backgroundColor": "#ff8200",
    "lineHeight": "22px",
    "position": "relative",
    "color": "white",
    width: "fit-content",
    touchAction: "manipulation",
    cursor: "pointer",
    border: "1px solid transparent",
    fontWeight: "600",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitFontSmoothing: "antialiased",
    backgroundImage: "none",
    display: "inline-flex",
    alignItems: "center",
    paddingLeft: "24px",
    paddingRight: "24px",
    fontSize: "18px",
    height: "auto",
    textDecoration: "none",
  },
  loginLink: {
    "flexDirection": "row",
    "borderRadius": "38px",
    "borderWidth": "0px",
    "padding": "0.5em 2em",
    margin: "1em",
    "lineHeight": "22px",
    "position": "relative",
    "color": "white",
    width: "fit-content",
    touchAction: "manipulation",
    cursor: "pointer",
    border: "1px solid transparent",
    fontWeight: "600",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitFontSmoothing: "antialiased",
    backgroundImage: "none",
    display: "inline-flex",
    alignItems: "center",
    paddingLeft: "24px",
    paddingRight: "24px",
    fontSize: "18px",
    height: "auto",
    textDecoration: "none",
    backgroundColor: "#42b029",
  },
  accountMessage: {
    margin: "12px auto",
    width: "fit-content",
    fontSize: "15px",
    color: "rgb(66, 66, 66)",
  },
  accountRedirect: {
    width: "fit-content",
    margin: "auto",
    padding: "0.5em",
  },
  appDescription: {
    "width": "fit-content",
    "fontSize": "23px",
    "lineHeight": "28px",
    margin: "auto",
    "marginTop": "2em",
    textAlign: "center",
    color: "rgb(114, 118, 126)",
  },
  curveDiv: {
    position: "relative",
    marginTop: "-3em",
    marginLeft: "-2em",
    marginRight: "-2em",
    "@media (min-width:800px)": {
      top: "-4em",
    },
    "@media (max-width:600px)": {
      top: "-2em",
    },
    "@media (max-width:500px)": {
      top: "-0.5em",
    },
    "@media (max-width:400px)": {
      top: "0.3em",
    },
    "@media (max-width:300px)": {
      top: "1.3em",
    },
  },
  curveDivBottom: {
    "transform": "scaleY(-1)",
    position: "relative",
    marginTop: "-3em",
    marginLeft: "-2em",
    // marginRight: "-2em",
    // "@media (min-width:800px)": {
    //   bottom: "-4em",
    // },
    // "@media (max-width:600px)": {
    //   bottom: "-2em",
    // },
    // "@media (max-width:500px)": {
    //   bottom: "-0.5em",
    // },
    // "@media (max-width:400px)": {
    //   bottom: "0.3em",
    // },
    // "@media (max-width:300px)": {
    //   bottom: "1.3em",
    // },
  },
  searchExample: {
    zIndex: "-3",
    position: "relative",
    margin: "-1em",
    backgroundColor: "#42b029",
    height: "fit-content",
  },
  searchBlob: {
    zIndex: "-1",
    position: "absolute",
    margin: "-2em",
    color: "white",
  },
  searchImg: {
    zIndex: "60",
    padding: "8em 1em",
    maxWidth: "90vw",
    maxHeight: "60vh",
    margin: "auto",
    "display": "block",
    "marginLeft": "auto",
    "marginRight": "auto",
  },
  searchHeader: {
    "margin": "0",
    "position": "absolute",
    "top": "15%",
    "left": "50%",
    "MsTransform": "translate(-50%, -0%)",
    "transform": "translate(-50%, -0%)"
  }
}))
