import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  formContainer: {
    marginTop: '2%',
    minHeight: '80vh',
  },
  form: {
    maxWidth: '750px',
    margin: 'auto',
    padding: '24px',
    marginBottom: '1vh',
    backgroundColor: 'white',
    borderRadius: '1vh',
    '@media (max-width:1000px)': {
      padding: '0',
      marginTop: '20px',
    },
  },
  itemDetails: {
    paddingLeft: '.9375rem',
    paddingRight: '.9375rem',
    gridRowGap: '15px',
    padding: '15px',
  },
  itemName: {
    gridColumnStart: '1',
    gridColumnEnd: '3',
    '& input': {
      color: 'rgb(57, 57, 57)',
      fontSize: '24px',
      fontWeight: '600',
      lineHeight: '32px',
      padding: '6px',
    },
  },
  itemSize: {
    width: '30vw',
    maxWidth: '175px',
    '& input': {
      margin: '0px',
      fontWeight: '400',
      color: 'rgb(142, 142, 142)',
      fontSize: '16px',
      lineHeight: '17px',
      padding: '6px',
    },
  },
  imageContainer: {
    position: 'relative',
    width: 'fit-content',
    margin: 'auto',
    height: 'max(10vh, auto)',
    minHeight: '160px',
    '& img': {
      maxWidth: '200px',
      maxHeight: '200px',
    },
    '& button': {
      content: '"X"',
      position: 'absolute',
      display: 'block',
      top: '0px',
      right: '-10px',
      borderRadius: '50%',
      height: '35px',
      width: '35px',
      color: '#e23535',
      backgroundColor: 'white',
      border: '3px solid #cc3131',
      fontSize: '1.3em',
      fontWeight: '900',
      '&:hover': {
        backgroundColor: '#f3f3f3',
        color: '#ab1515',
        border: '3px solid #ab1515',
        boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
      },
    },
  },
  itemPrice: {
    '& input': {
      fontSize: '26px',
      lineHeigt: '26px',
      fontWeight: '700',
      padding: '6px',
    },
  },
  priceIndicator: {
    position: 'absolute',
    fontSize: '26px',
    margin: '0',
    padding: '0',
    left: '-15px',
    bottom: '15px',
  },
  itemPriority: {
    margin: 'inherit',
  },
  dollarSign: {
    position: 'relative',
    width: '50%',
    marginLeft: 'auto',
    '& div': {
      marginTop: '0',
    },
  },
  divLabel: {
    fontSize: '13px',
    padding: '0',
    color: '#403e3e',
  },
  itemServing: {
    color: '#3c78a5',
    '& input': {
      color: '#3c78a5',
    },
  },
  itemDate: {
    width: 'fit-content',
    marginLeft: 'auto',
  },
  updateButton: {
    marginTop: '15px',
    width: 'fit-content',
    padding: '1em 5em',
    margin: 'auto',
    fontWeight: '800',
    backgroundColor: '#32b31a',
    '&:hover': {
      backgroundColor: '#2d9819',
    },
    '@media (max-width:450px)': {
      padding: '1em 3em',
    },
  },
  deleteButton: {
    marginTop: '15px',
    width: 'fit-content',
    padding: '1em 5em',
    margin: 'auto',
    fontWeight: '800',
    backgroundColor: '#f50057',
    '&:hover': {
      backgroundColor: '#cd044b',
    },
    '@media (max-width:450px)': {
      padding: '1em 3em',
    },
  },
  fileInput: {
    outlineOffset: '-10px',
    height: '200px',
    margin: 'auto',
    display: 'block',
    '& div': {
      backgroundColor: '#f5f5f5',
      border: '2px dashed #b7b7b7',
      height: '100%',
      width: 'fit-content',
      margin: 'auto',
      position: 'relative',
    },
    '& input': {
      width: '80%',
      padding: '15px',
      color: '#0f690f',
      margin: 'auto',
      minHeight: '200px',
    },
  },
  newCategoryBtn: {
    'padding': '0px 6px',
    'margin': 'auto',
    'color': 'white',
    'background': '#ff9749',
    'fontWeight': '500',
    'fontSize': '24px',
    'border': 'none',
    'borderRadius': '5px',
    'top': '22px',
    'position': 'absolute',
    '&:hover': {
      backgroundColor: '#d47b39',
    },
  },
  itemCategory: {
    position: 'relative',
  },
  popupContainer: {
    'position': 'fixed',
    'top': '0',
    'bottom': '0',
    'left': '0',
    'right': '0',
    'background': 'rgba(0, 0, 0, 0.7)',
    'transition': 'opacity 500ms',
    zIndex: '200',
  },
  popupElement: {
    'visibility': 'visible',
    'opacity': '1',
    'margin': '70px auto',
    'padding': '20px',
    'background': '#fff',
    'borderRadius': '5px',
    'width': '60%',
    'transition': 'all 5s ease-in-out',
    minWidth: '300px',
    minHeight: '70vh',
    height: 'fit-content',
  },
  productGrid: {
    display: 'grid',
    gridTemplateColumns: '40% auto',
    justifyContent: 'space-around',
    '@media (max-width:900px)': {
      gridTemplateColumns: 'auto',
      margin: 'auto',
      textAlign: 'center',
    },
  },
  productImage: {
    '@media (max-width:900px)': {
      width: '70%',
    },
    margin: 'auto',
    objectFit: 'cover',
    maxHeight: '250px',
    minHeight: '100px',
    columnFill: 'auto',
    'gridRowStart': '1',
    'gridRowEnd': '2'
  },
  productRating: {
    '@media (max-width:900px)': {
      gridRowStart: '2',
      gridRowEnd: '3',
      gridColumnStart: '0',
    },
    width: 'fit-content',
    margin: 'auto',
    marginTop: '5px',
  },
  foodName: {
    '@media (max-width:900px)': {
      marginTop: '0',
      display: 'block',
      marginBottom: '15px',
    },
    marginTop: '10px',
    marginBottom: '5px',
    height: 'fit-content',
    fontSize: '1.5em',
    color: '#4f4e4e',
  },
  cartIcon: {
    paddingTop: '4px',
  },
  addButton: {
    '@media (max-width:900px)': {
      gridRowStart: '5',
      gridRowEnd: '6',
      gridColumnStart: '0',
    },
    // height: '42px',
    width: 'fit-content',
    fontSize: '1.2em',
    backgroundColor: 'rgb(67, 176, 42)',
    border: '1px solid rgb(67, 176, 42)',
    borderRadius: '25px',
    touchAction: 'manipulation',
    fontWeight: '200',
    color: 'white',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    webkitFontSmoothing: 'antialiased',
    backgroundImage: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    zIndex: '2',
    padding: '10px 20px 10px 20px',
    margin: ' 5px auto 5px auto',
    justifyContent: 'center',
    '&:hover': {
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
    },
  },
  editButton: {
    '@media (max-width:900px)': {
      gridRowStart: '6',
      gridRowEnd: '7',
      gridColumnStart: '0',
    },
    width: 'fit-content',
    fontSize: '1.2em',
    backgroundColor: 'white',
    border: '1px solid rgb(154 97 27)',
    borderRadius: '5px',
    touchAction: 'manipulation',
    fontWeight: '200',
    color: 'rgb(241 154 47)',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    webkitFontSmoothing: 'antialiased',
    backgroundImage: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    zIndex: '2',
    padding: '10px 20px 10px 20px',
    margin: ' 5px auto 5px auto',
    justifyContent: 'center',
    '&:hover': {
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
    },
  },
  productDetails: {
    '@media (max-width:900px)': {
      textAlign: 'left',
      gridRowStart: '4',
      gridRowEnd: '5',
      marginBottom: '15px',
    },
  },
  foodPrice: {
    '@media (max-width:900px)': {
      float: 'right',
    },
    'color': '#929292',
    width: 'fit-content',
    'fontWeight': '400',
    display: 'block',
    'margin': 'auto',
    'fontSize': '1.7em'
  },
  productSpecification: {
    display: 'block',
    color: '#4f4e4e',
    padding: '2px',
    margin: '0',
  },
  foodBrand: {
    'background': '#eeeeee',
    'width': 'fit-content',
    'padding': '0.3em',
    'margin': '1px',
    'border': '1px solid white',
    'color': '#4f4d4b',
    'borderRadius': '5px'
  },
  popupSearchBar: {
    margin: 'auto',
    width: '90%',
  },
  searchResultCards: {
    "&::-webkit-scrollbar": {
      background: 'white',
    },
    width: 'fit-content',
    padding: '0',
    margin: 'auto',
    marginTop: '2em',
    overflowY: 'scroll',
    display: 'grid',
    gridTemplateColumns: 'auto auto auto',
    maxHeight: '70vh',
    '@media (max-width:900px)': {
      gridTemplateColumns: 'auto auto',
    },
    '@media (max-width:640px)': {
      gridTemplateColumns: 'auto',
    },
  },
}));