import { makeStyles } from "@material-ui/core/styles"

export default makeStyles((theme) => ({
  demoImg: {
    maxWidth: "90vw",
    maxHeight: "50vh",
    margin: "auto",
    "display": "block",
    "marginLeft": "auto",
    "marginRight": "auto",
  },
  accountLink: {
    "flexDirection": "row",
    "borderRadius": "38px",
    "borderWidth": "0px",
    "padding": "0.5em 2em",
    margin: "1em",
    "backgroundColor": "#ff8200",
    "lineHeight": "22px",
    "position": "relative",
    "color": "white",
    width: "fit-content",
    touchAction: "manipulation",
    cursor: "pointer",
    border: "1px solid transparent",
    fontWeight: "600",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitFontSmoothing: "antialiased",
    backgroundImage: "none",
    display: "inline-flex",
    alignItems: "center",
    paddingLeft: "24px",
    paddingRight: "24px",
    fontSize: "18px",
    height: "auto",
    textDecoration: "none",
  },
  loginLink: {
    "flexDirection": "row",
    "borderRadius": "38px",
    "borderWidth": "0px",
    "padding": "0.5em 2em",
    margin: "1em",
    "lineHeight": "22px",
    "position": "relative",
    "color": "white",
    width: "fit-content",
    touchAction: "manipulation",
    cursor: "pointer",
    border: "1px solid transparent",
    fontWeight: "600",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitFontSmoothing: "antialiased",
    backgroundImage: "none",
    display: "inline-flex",
    alignItems: "center",
    paddingLeft: "24px",
    paddingRight: "24px",
    fontSize: "18px",
    height: "auto",
    textDecoration: "none",
    backgroundColor: "#42b029",
  },
  accountMessage: {
    margin: "12px auto",
    width: "fit-content",
    fontSize: "15px",
    color: "rgb(66, 66, 66)",
  },
  accountRedirect: {
    width: "fit-content",
    margin: "auto",
    padding: "0.5em",
  },
  appDescription: {
    "width": "fit-content",
    "fontSize": "23px",
    "lineHeight": "28px",
    margin: "auto",
    "marginTop": "2em",
    color: "rgb(114, 118, 126)",
  }
}))
