import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(() => ({
  bubbleAddBtn: {
    zIndex: '10',
    height: '42px',
    width: '42px',
    fontSize: '2.5em',
    color: 'rgb(67, 176, 42)',
    backgroundColor: 'white',
    border: '1px solid rgb(67, 176, 42)',
    borderRadius: '50%',
    position: 'absolute',
    top: '-4px',
    right: '-8px',
    touchAction: 'manipulation',
    fontWeight: '100',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    webkitFontSmoothing: 'antialiased',
    backgroundImage: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0px',
    justifyContent: 'center',
    '&:hover': {
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
    },
  },
  addToCartBtn: {
    '@media (max-width:900px)': {
      gridRowStart: '5',
      gridRowEnd: '6',
      gridColumnStart: '0',
    },
    width: 'fit-content',
    fontSize: '1.2em',
    backgroundColor: 'rgb(67, 176, 42)',
    border: '1px solid rgb(67, 176, 42)',
    borderRadius: '25px',
    touchAction: 'manipulation',
    fontWeight: '200',
    color: 'white',
    height: 'fit-content',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    webkitFontSmoothing: 'antialiased',
    backgroundImage: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    zIndex: '10',
    padding: '10px 20px 10px 20px',
    margin: ' 5px auto 5px auto',
    justifyContent: 'center',
    '&:hover': {
      boxShadow: 'rgba(0, 0, 0, 0.1) 0px 0px 0px 4px',
    },
  },
}));
