import { makeStyles } from "@material-ui/core/styles"

export default makeStyles(() => ({
  loginPrompt: {
    // '&::after': {
    //   zIndex: "90",
    //   content: "' '",
    //   backgroundColor: "rgba(0, 0, 0, 0.6)",
    //   position: "fixed",
    //   top: "0",
    //   left: "0",
    //   height: "100vh",
    //   width: "100vw",
    // },
    zIndex: "99",
    backgroundColor: "white",
    margin: "auto",
    marginTop: "20vh",
    marginBottom: "40vh",
    // minHeight: "136px",
    padding: "30px",
    borderRadius: "8px",
    width: "fit-content",
    "@media (max-width:900px)": {
      marginBottom: "30vh",
    },
    "& input": {
      zIndex: "99",
      backgroundColor: "rgb(255, 255, 255)",
      border: "1px solid rgb(189, 189, 189)",
      borderRadius: "12px",
      boxSizing: "border-box",
      color: "rgb(66, 66, 66)",
      fontSize: "16px",
      height: "56px",
      padding: "20px 8px 8px",
      position: "relative",
      width: "100%",
      opacity: "1",
      WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
      backgroundRepeat: "no-repeat",
      backgroundAttachment: "scroll",
      backgroundSize: "16px 18px",
      backgroundPosition: "98% 50%",
      cursor: "auto",
      margin: "20px auto",
    },
  },
  loginButton: {
    zIndex: "99",
    touchAction: "manipulation",
    cursor: "pointer",
    border: "1px solid transparent",
    borderRadius: "4px",
    fontWeight: "600",
    whiteSpace: "nowrap",
    userSelect: "none",
    WebkitFontSmoothing: "antialiased",
    backgroundImage: "none",
    display: "block",
    alignItems: "center",
    paddingLeft: "16px",
    paddingRight: "16px",
    fontSize: "18px",
    height: "40px",
    backgroundColor: "rgb(46, 137, 19)",
    color: "rgb(255, 255, 255)",
    width: "100%",
  },
  passwordLabel: {
    zIndex: "99",
    fontSize: "31px",
    fontWeight: "700",
    marginBottom: "0",
  },
}))
