const todaysDate = new Date().toISOString().slice(0, 10);

const nutriscoreSchema = {
  grade: "",
  score: 0,
  energy: 0,
  energy_points: 0,
  energy_value: 0,
  fiber: 0,
  fiber_points: 0,
  fiber_value: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
  is_beverage: 0,
  is_cheese: "0",
  is_fat: 0,
  is_water: 0,
  negative_points: 0,
  positive_points: 0,
  proteins: 0,
  proteins_points: 0,
  proteins_value: 0,
  saturated_fat: 0,
  saturated_fat_points: 0,
  saturated_fat_ratio: 0,
  saturated_fat_ratio_points: 0,
  saturated_fat_ratio_value: 0,
  saturated_fat_value: 0,
  sodium: 0,
  sodium_points: 0,
  sodium_value: 0,
  sugars: 0,
  sugars_points: 0,
  sugars_value: 0,
}

const grocerySchema = {
  name: "unknown",
  purchase_price: "0.01",
  purchase_size: "0 oz",
  serving_cost: "0.01",
  category: "unknown",
  last_purchased: todaysDate,
  priority: "3",
  upc: "",
  image: "",
  _id: "",
  brand: "unknown",
  ingredients: [],
  nutriscore_data: nutriscoreSchema,
  nutriscore_data_per: "0.1 g",
  nutriscore_data_prepared_per: "0.1 g",
  quantity: "0.1 g",
  serving_size: "0.1 g",
  serving_quantity: 1,
  unit_size: "1 unit",
}

export default grocerySchema