const nutriscoreSchema = {
  grade: "",
  score: 0,
  energy: 0,
  energy_points: 0,
  energy_value: 0,
  fat: 0,
  fiber: 0,
  fiber_points: 0,
  fiber_value: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
  fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
  is_beverage: 0,
  is_cheese: "0",
  is_fat: 0,
  is_water: 0,
  negative_points: 0,
  positive_points: 0,
  proteins: 0,
  proteins_points: 0,
  proteins_value: 0,
  "saturated-fat": 0,
  saturated_fat_points: 0,
  saturated_fat_ratio: 0,
  saturated_fat_ratio_points: 0,
  saturated_fat_ratio_value: 0,
  saturated_fat_value: 0,
  sodium: 0,
  sodium_points: 0,
  sodium_value: 0,
  sugars: 0,
  sugars_points: 0,
  sugars_value: 0,
  "trans-fat": 0,
  cholesterol: 0,
  "total_carbs": 0,
  calories: 0,
  carbohydrates_serving: 0,
  dietary_fiber: 0,
  protein: 0,
  "vitamin-a": 0,
  "vitamin-c": 0,
  calcium: 0,
  iron: 0,
  serving_size: "~1 oz",
  serving_quantity: 1,
}

export default nutriscoreSchema